Repository CMSgov/blueprint_ui, pull requests merged in 2022-09, with the labels that each got.

#88 Formatting catalog titles to be human friendly
  src/Helpers.js
  src/Helpers.test.js
  src/templates/SearchLibrary.jsx
Labels: bug

#93 [1245] Updating documentation for future development
  Dockerfile
  README.md
Labels: documentation

#97 feature/1017 update private narratives
  public/logo192.png
  public/logo512.png
  src/App.scss
  src/atoms/Tooltip.jsx
  src/info.png
  src/pages/Control.jsx
  src/pages/Control.test.jsx
  src/templates/ControlTemplate.jsx
  src/templates/ControlTemplate.test.jsx
Labels: enhancement
